Repository DSM-PICK/PiCK_CORE_SERVER, pull requests merged in 2024-01, with the labels that each got.

#6 🔀 :: (PICK-5) develop global
  buildSrc/src/main/kotlin/PluginVersions.kt
  buildSrc/src/test/kotlin/dsm/buildsrc/BuildSrcApplicationTests.kt
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/dsm/pick2024_server/Pick2024ServerApplication.kt
  src/main/kotlin/dsm/pick2024_server/domain/example/domain/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/entity/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/exception/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/mapper/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/persistence/repository/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/example/port/out/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/user/domain/User.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/entity/UserJpaEntity.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/mapper/UserMapper.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/persistence/UserPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/persistence/repository/UserRepository.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/port/in/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/user/port/out/UserByNamePort.kt
  src/main/kotlin/dsm/pick2024_server/domain/user/presentation/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/user/presentation/dto/request/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/user/presentation/dto/response/.gitkeep
  src/main/kotlin/dsm/pick2024_server/domain/user/service/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/base/BaseTimeEntity.kt
  src/main/kotlin/dsm/pick2024_server/global/base/BaseUUIDEntity.kt
  src/main/kotlin/dsm/pick2024_server/global/config/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/config/filter/FilterConfig.kt
  src/main/kotlin/dsm/pick2024_server/global/config/redis/RedisConfig.kt
  src/main/kotlin/dsm/pick2024_server/global/config/security/SecurityConfig.kt
  src/main/kotlin/dsm/pick2024_server/global/error/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/error/ErrorResponse.kt
  src/main/kotlin/dsm/pick2024_server/global/error/GlobalExceptionFilter.kt
  src/main/kotlin/dsm/pick2024_server/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/dsm/pick2024_server/global/error/exception/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/error/exception/ErrorCode.kt
  src/main/kotlin/dsm/pick2024_server/global/error/exception/PickException.kt
  src/main/kotlin/dsm/pick2024_server/global/security/.gitkeep
  src/main/kotlin/dsm/pick2024_server/global/security/auth/AuthDetails.kt
  src/main/kotlin/dsm/pick2024_server/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/JwtProperties.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/JwtTokenFilter.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/dto/TokenResponse.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/entity/RefreshToken.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/entity/repository/RefreshTokenRepository.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/exception/ExpiredTokenException.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/exception/InternalServerErrorException.kt
  src/main/kotlin/dsm/pick2024_server/global/security/jwt/exception/InvalidJwtException.kt
Labels: 기능 개발

#14 🔀 :: (PICK-9) add user table
  src/main/kotlin/dsm/pick2024/domain/user/domain/User.kt
  src/main/kotlin/dsm/pick2024/domain/user/entity/UserJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/user/entity/enums/Role.kt
  src/main/kotlin/dsm/pick2024/domain/user/mapper/UserMapper.kt
Labels: core

#15 🔀 :: (PICK-10)add admin table
  src/main/kotlin/dsm/pick2024/domain/admin/domain/Admin.kt
  src/main/kotlin/dsm/pick2024/domain/admin/entity/AdminJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/admin/exception/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/mapper/AdminMapper.kt
  src/main/kotlin/dsm/pick2024/domain/admin/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/persistence/repository/AdminRepository.kt
  src/main/kotlin/dsm/pick2024/domain/admin/port/in/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/port/out/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/presentation/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/presentation/dto/request/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/admin/presentation/dto/response/.gitkeep
Labels: core

#16 🔀 :: (PICK-11) 11 add meal table
  src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
  src/main/kotlin/dsm/pick2024/domain/meal/entity/MealJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/meal/exception/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/mapper/MealMapper.kt
  src/main/kotlin/dsm/pick2024/domain/meal/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/persistence/repository/MealRepository.kt
  src/main/kotlin/dsm/pick2024/domain/meal/port/in/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/port/out/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/presentation/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/request/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/meal/service/.gitkeep
Labels: core

#20 🔀 :: (PICK-13) add notice entity
  src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
  src/main/kotlin/dsm/pick2024/domain/notice/entity/NoticeJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/notice/exception/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/mapper/NoticeMapper.kt
  src/main/kotlin/dsm/pick2024/domain/notice/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/persistence/repository/NoticeRepository.kt
  src/main/kotlin/dsm/pick2024/domain/notice/port/in/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/port/out/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/request/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/notice/service/.gitkeep
  src/main/kotlin/dsm/pick2024/global/security/jwt/exception/ExpiredTokenException.kt
Labels: core

#23 🔀 :: (PICK-19) querydsl setting
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
Labels: 프로젝트 세팅

#24 🔀 :: (PICK-17) add status entity
  src/main/kotlin/dsm/pick2024/domain/status/domain/Status.kt
  src/main/kotlin/dsm/pick2024/domain/status/entity/StatusJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/status/entity/enum/StatusType.kt
  src/main/kotlin/dsm/pick2024/domain/status/mapper/StatusMapper.kt
  src/main/kotlin/dsm/pick2024/domain/status/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/status/persistence/repository/StatusRepository.kt
Labels: core

#25 🔀 :: (PICK-12) add application entity
  src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
  src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
  src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
  src/main/kotlin/dsm/pick2024/domain/application/persistence/.gitkeep
  src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
Labels: core
