Repository DSM-PICK/PiCK_CORE_SERVER, pull requests merged in 2024-09, with the labels that each got.

#356 🔀 :: (PiCK-145) fcm setting
  .gitignore
  build.gradle.kts
  dump.rdb
  src/main/kotlin/dsm/pick2024/global/config/fcm/FcmConfig.kt
  src/main/resources/application.yaml
Labels: 프로젝트 세팅

#359 🔀 :: (PiCK-358) application earlyreturn classroom dto
  src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/response/QueryMyApplicationResponse.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryMyApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/request/UserMoveClassroomRequest.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/presentation/dto/response/QueryMainUserMoveClassroomResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryMyEarlyReturnResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
Labels: Refactoring

#360 🔀 :: (PiCK-357) fcm notice
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  src/main/kotlin/dsm/pick2024/domain/event/Topic.kt
  src/main/kotlin/dsm/pick2024/domain/event/notice/SendMessageToNoticeEvent.kt
  src/main/kotlin/dsm/pick2024/domain/event/notice/SendMessageToNoticeEventPort.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/CreateNoticeService.kt
  src/main/kotlin/dsm/pick2024/domain/notification/domain/TopicSubscription.kt
  src/main/kotlin/dsm/pick2024/domain/notification/entity/TopicSubscriptionJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/notification/event/CreateSubscribeTopicEvent.kt
  src/main/kotlin/dsm/pick2024/domain/notification/event/CreateSubscribeTopicEventPort.kt
  src/main/kotlin/dsm/pick2024/domain/notification/mapper/TopicSubscriptionMapper.kt
  src/main/kotlin/dsm/pick2024/domain/notification/persistence/TopicSubscriptionPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/notification/persistence/repository/TopicSubscriptionRepository.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/in/ChangeTopicUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/in/QueryMySubscribeTopicUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/out/CommendTopicSubscriptionPort.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/out/QueryTopicSubscriptionPort.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/out/SaveTopicSubscriptionPort.kt
  src/main/kotlin/dsm/pick2024/domain/notification/port/out/TopicSubscriptionPort.kt
  src/main/kotlin/dsm/pick2024/domain/notification/presentation/NotificationController.kt
  src/main/kotlin/dsm/pick2024/domain/notification/presentation/dto/request/ChangeSubscribeTopicRequest.kt
  src/main/kotlin/dsm/pick2024/domain/notification/presentation/dto/request/Notification.kt
  src/main/kotlin/dsm/pick2024/domain/notification/presentation/dto/response/QueryMySubscribeTopicResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notification/service/ChangeSubscribeTopicService.kt
  src/main/kotlin/dsm/pick2024/domain/notification/service/QueryMySubscribeTopicService.kt
  src/main/kotlin/dsm/pick2024/domain/user/domain/User.kt
  src/main/kotlin/dsm/pick2024/domain/user/entity/UserJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/user/mapper/UserMapper.kt
  src/main/kotlin/dsm/pick2024/domain/user/persistence/repository/UserRepository.kt
  src/main/kotlin/dsm/pick2024/domain/user/presentation/dto/request/UserLoginRequest.kt
  src/main/kotlin/dsm/pick2024/domain/user/service/UserLoginService.kt
  src/main/kotlin/dsm/pick2024/global/config/fcm/FcmConfig.kt
  src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
  src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
  src/main/kotlin/dsm/pick2024/infrastructure/util/FcmUtil.kt
  src/main/kotlin/dsm/pick2024/infrastructure/util/exception/FcmServerException.kt
  src/main/resources/application.yaml
Labels: 기능 개발

#366 🔀 :: (PiCK-365)main waiting response
  src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/out/ExistsApplicationPort.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryApplicationPort.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/ApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryMyApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/CreateEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
Labels: 기능 개발

#371 🔀 :: (PiCK-370) admin timetable
  src/main/kotlin/dsm/pick2024/domain/timetable/port/in/QueryDayTimetableUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/port/in/QueryTeacherTimetableUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/port/in/QueryWeekTimetableUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/TimetableController.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/request/QueryTeacherTimetableRequest.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/response/TimetableResponse.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTeacherTimetableService.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTimetableService.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryWeekTimetableService.kt
  src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
Labels: 기능 개발

#373 🔀 :: (PiCK-370) modify timetable
  src/main/kotlin/dsm/pick2024/domain/timetable/exception/TimetableNotFoundException.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/peristence/TimetablePersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/peristence/repository/TimetableRepository.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/port/in/ModifyTimetableUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/port/out/QueryTimeTablePort.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/port/out/SaveTimetablePort.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/TimetableController.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/request/ChangeTimetableRequest.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/ModifyTimetableService.kt
  src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
Labels: 기능 개발

#378 🔀 :: (PiCK-377) timetable all refactoring
  src/main/kotlin/dsm/pick2024/domain/timetable/port/in/QueryTeacherTimetableUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/TimetableController.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/request/QueryTeacherTimetableRequest.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTeacherTimetableService.kt
Labels: Refactoring

#382 🔀 :: (PiCK-381) admin timetable error
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTeacherTimetableService.kt
Labels: bug
