Repository DSM-PICK/PiCK_CORE_SERVER, pull requests merged in 2024-05, with the labels that each got.

#152 🔀 :: (PICK-151)classroom auto status change
  src/main/kotlin/dsm/pick2024/domain/attendance/port/out/AttendancePort.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/out/FindAttendanceByUserIdPort.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/ChangeAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/ChangeClassroomStatusService.kt
  src/main/kotlin/dsm/pick2024/domain/meal/service/SaveMealService.kt
Labels: 기능 개발

#154 Error security
  Dockerfile
  src/main/kotlin/dsm/pick2024/domain/admin/domain/Admin.kt
  src/main/kotlin/dsm/pick2024/domain/admin/presentation/dto/response/QueryAdminNameResponse.kt
  src/main/kotlin/dsm/pick2024/domain/admin/service/QueryAdminAllService.kt
  src/main/kotlin/dsm/pick2024/domain/admin/service/QueryAdminNameService.kt
  src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
  src/main/kotlin/dsm/pick2024/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/dsm/pick2024/infrastructure/discord/DiscordComponet.kt
  src/main/kotlin/dsm/pick2024/infrastructure/feign/client/DiscordProdClient.kt
  src/main/kotlin/dsm/pick2024/infrastructure/feign/client/DiscordStagClient.kt
  src/main/resources/application.yaml
Labels: bug

#157 🔀 :: (PICK-156)156 error report bug
  src/main/kotlin/dsm/pick2024/domain/bug/AddBugService.kt
Labels: bug

#161 Add annotation
  src/main/kotlin/dsm/pick2024/domain/admin/domain/Admin.kt
  src/main/kotlin/dsm/pick2024/domain/afterschool/domain/AfterSchoolStudent.kt
  src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
  src/main/kotlin/dsm/pick2024/domain/applicationstory/domain/ApplicationStory.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/domain/Attendance.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/domain/Classroom.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/domain/EarlyReturn.kt
  src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
  src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/domain/Schedule.kt
  src/main/kotlin/dsm/pick2024/domain/selfstudy/domain/SelfStudy.kt
  src/main/kotlin/dsm/pick2024/domain/status/domain/Status.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/domain/Timetable.kt
  src/main/kotlin/dsm/pick2024/domain/user/domain/User.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/domain/WeekendMeal.kt
  src/main/kotlin/dsm/pick2024/global/annotation/Aggregate.kt
  src/main/kotlin/dsm/pick2024/global/annotation/ReadOnlyUseCase.kt
  src/main/kotlin/dsm/pick2024/global/annotation/UseCase.kt
Labels: 프로젝트 세팅

#166 🔀 :: (PICK-165)change attendance response
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAttendanceResponse.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/status/presentation/dto/response/QueryClassStatusResponse.kt
  src/main/kotlin/dsm/pick2024/domain/status/service/QueryClassStatusService.kt
Labels: 기능 개발

#172 🔀 :: (PICK-171)modify-search-move-calssroom-bug
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
Labels: bug

#174 🔀 :: (PICK-173)dsave all weekend meal user meal service refactor
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/out/SaveAllWeekendMealPort.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/ResetWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/SaveAllWeekendMealUserMealService.kt
Labels: Refactoring

#179 🔀 :: (PICK-178)modify wrong import
  src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryClassUserService.kt
Labels: Refactoring

#181 🔀 :: (PICK-180)modify :: findByUserIdOrderByDateDesc
  src/main/kotlin/dsm/pick2024/domain/applicationstory/persistence/ApplicationStoryPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
Labels: 기능 개발
