Repository DSM-PICK/PiCK_CORE_SERVER, pull requests merged in 2024-07, with the labels that each got.

#213 🔀 :: (PiCK-212)refactor :: userId -> id
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/presentation/WeekendMealController.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/QueryAllWeekendMealStatus.kt
Labels: Refactoring

#215 🔀 :: (PICK-214)classroom startplace error
  src/main/kotlin/dsm/pick2024/domain/attendance/persistence/AttendancePersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/persistence/repository/AttendanceRepository.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/out/QueryAttendancePort.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/persistence/PersistenceAdapterClassRoom.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/port/out/QueryClassroomPort.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryGradeClassroomService.kt
Labels: bug

#217 🔀 :: (PICK-216)modify :: floor5 logic
  src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryFloorClassroomService.kt
Labels: bug

#222 🔀 :: (PICK-221)many schedule error
  src/main/kotlin/dsm/pick2024/domain/schedule/persistence/SchedulePersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/persistence/repository/ScheduleRepository.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/port/in/QueryDateScheduleUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/port/out/QuerySchedulePort.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/service/QueryDateScheduleService.kt
Labels: bug

#225 🔀 :: (PICK-224)query floor application student
  src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/application/persistence/repository/ApplicationRepository.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorAndStatusApplicationUseCase.kt.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/in/QueryFloorApplicationUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/out/QueryApplicationPort.kt
  src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryFloorApplicationService.kt
Labels: 기능 개발

#227 🔀 :: (PICK-226)modify :: findBy -> findOKClassroom
  src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAttendanceService.kt
Labels: bug

#238 🔀 :: (PICK-236)add :: refresh path
  src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
Labels: bug

#240 🔀 :: (PICK-236) add earlyReturn count
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryStatusApplicationService.kt
Labels: 기능 개발

#244 🔀 :: (PICK-243)class all application sort
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryClassApplicationService.kt
Labels: bug

#249 🔀 :: (PiCK-247)ttl customization
  src/main/kotlin/dsm/pick2024/global/config/cache/CacheConfig.kt
Labels: 기능 개발

#251 🔀 :: (PiCK-250)status attendnace sync
  src/main/kotlin/dsm/pick2024/domain/afterschool/domain/AfterSchoolStudent.kt
  src/main/kotlin/dsm/pick2024/domain/afterschool/entity/AfterSchoolStudentJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/afterschool/presentation/dto/request/ChangeAfterSchoolStatusRequest.kt
  src/main/kotlin/dsm/pick2024/domain/afterschool/presentation/dto/response/QueryAfterSchoolStudentAllResponse.kt
  src/main/kotlin/dsm/pick2024/domain/afterschool/service/SaveAfterSchoolStudentService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/domain/Attendance.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/entity/AttendanceJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/enums/AttendanceStatus.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/persistence/AttendancePersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/persistence/repository/AttendanceRepository.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/out/AttendancePort.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/out/SaveAttendancePort.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/request/ChangeAttendanceRequest.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAttendanceResponse.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/ChangeAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/ResetAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/ChangeClassroomStatusService.kt
  src/main/kotlin/dsm/pick2024/domain/status/service/ChangeStatusService.kt
Labels: 기능 개발

#254 🔀 :: (PiCK-253)status error
  src/main/kotlin/dsm/pick2024/domain/status/service/ChangeStatusService.kt
Labels: bug

#256 🔀 :: (PiCK-255)refactor classname
  src/main/kotlin/dsm/pick2024/domain/application/port/in/ChangeApplicationStatusUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/in/ReturnApplicationStatusUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/application/port/in/StatusApplicationChangeUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/ChangeApplicationStatusService.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/ReturnApplicationReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/in/ResetAttendanceUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/ResetAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/port/in/BackUserClassroomUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/port/in/MoveClassroomApplicationUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/presentation/ClassroomController.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/BackUserClassroomService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/MoveClassroomApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryUserMoveClassroomService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/port/in/ChangeEarlyReturnStatusUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/EarlyReturnController.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/ChangeEarlyReturnStatusService.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/port/in/QueryMonthScheduleUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/port/in/SaveScheduleUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/service/QueryMonthScheduleService.kt
  src/main/kotlin/dsm/pick2024/domain/schedule/service/SaveScheduleService.kt
  src/main/kotlin/dsm/pick2024/domain/selfstudy/port/in/RegistrationSelfStudyTeacherUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/selfstudy/presentation/SelfStudyController.kt
  src/main/kotlin/dsm/pick2024/domain/selfstudy/service/RegistrationSelfStudyTeacherService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/in/PrintExcelWeekendMealUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/presentation/WeekendMealController.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/CreateWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/PrintExcelWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/global/annotation/Aggregate.kt
  src/main/kotlin/dsm/pick2024/global/annotation/ReadOnlyUseCase.kt
  src/main/kotlin/dsm/pick2024/global/annotation/UseCase.kt
  src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
Labels: Refactoring

#259 🔀 :: (PiCK-258)timetable image return
  src/main/kotlin/dsm/pick2024/domain/timetable/presentation/dto/TimetableResponse.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryTimetableService.kt
  src/main/kotlin/dsm/pick2024/domain/timetable/service/QueryWeekTimetableService.kt
  src/main/kotlin/dsm/pick2024/infrastructure/s3/PathList.kt
Labels: 기능 개발
