Repository DSM-PICK/PiCK_CORE_SERVER, pull requests merged in 2024-08, with the labels that each got.

#262 🔀 :: (PiCK-261)application status delete
  src/main/kotlin/dsm/pick2024/domain/application/domain/Application.kt
  src/main/kotlin/dsm/pick2024/domain/application/entity/ApplicationJapEntity.kt
  src/main/kotlin/dsm/pick2024/domain/application/mapper/ApplicationMapper.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/ChangeApplicationStatusService.kt
Labels: Refactoring

#264 🔀 :: (PiCK-263)notice grade delete
  src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
  src/main/kotlin/dsm/pick2024/domain/notice/entity/NoticeJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/notice/mapper/NoticeMapper.kt
  src/main/kotlin/dsm/pick2024/domain/notice/port/in/QueryAllNoticeUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/request/ModifyNoticeRequest.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/request/NoticeRequest.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/QueryAllNoticeResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/QuerySimpleNoticeResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/QueryTodayNoticeResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/CreateNoticeService.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/ModifyNoticeService.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/QueryNoticeService.kt
Labels: Refactoring

#267 🔀 :: (PiCK-265)applicationstory return empty
  src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryUserApplicationStoryService.kt
  src/main/kotlin/dsm/pick2024/domain/user/persistence/UserPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/user/port/out/QueryUserPort.kt
Labels: 기능 개발

#269 🔀 :: (PiCK-268)notice local date time
  src/main/kotlin/dsm/pick2024/domain/notice/domain/Notice.kt
  src/main/kotlin/dsm/pick2024/domain/notice/entity/NoticeJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/notice/persistence/NoticePersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/QueryAllNoticeResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notice/presentation/dto/response/QuerySimpleNoticeResponse.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/CreateNoticeService.kt
  src/main/kotlin/dsm/pick2024/domain/notice/service/QueryNoticeService.kt
Labels: 기능 개발

#271 🔀 :: (PiCK-270)class attendance error
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/user/persistence/repository/UserRepository.kt
Labels: bug

#279 🔀 :: (PiCK-278) :: 당일 공지사항 조회
  dump.rdb
  src/main/kotlin/dsm/pick2024/domain/notice/persistence/NoticePersistenceAdapter.kt
Labels: bug

#288 🔀 :: (PiCK-285)add gohome enum
  src/main/kotlin/dsm/pick2024/domain/attendance/enums/AttendanceStatus.kt
Labels: 기능 개발

#292 🔀 :: (PiCK-285)291 main waiting
  src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
  src/main/kotlin/dsm/pick2024/domain/main/WaitingResponse.kt
Labels: 기능 개발

#294 🔀 :: (PiCK-293)add kcal modify table
  src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
  src/main/kotlin/dsm/pick2024/domain/meal/entity/MealJpaEntity.kt
  src/main/kotlin/dsm/pick2024/domain/meal/enum/MealType.kt
  src/main/kotlin/dsm/pick2024/domain/meal/mapper/MealMapper.kt
  src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/MealDetailsResponse.kt
  src/main/kotlin/dsm/pick2024/domain/meal/service/QueryDayMealService.kt
  src/main/kotlin/dsm/pick2024/domain/meal/service/SaveMealService.kt
  src/main/kotlin/dsm/pick2024/infrastructure/feign/NeisMealFeignClientService.kt
Labels: 기능 개발

#296 🔀 :: (PiCK-295)change meal response
  src/main/kotlin/dsm/pick2024/domain/meal/domain/Meal.kt
  src/main/kotlin/dsm/pick2024/domain/meal/presentation/dto/response/MealDetailsResponse.kt
  src/main/kotlin/dsm/pick2024/domain/meal/service/QueryDayMealService.kt
Labels: bug

#298 🔀 :: (PiCK-297)application story query error
  src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryUserApplicationStoryService.kt
  src/main/kotlin/dsm/pick2024/domain/user/persistence/UserPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/user/persistence/repository/UserRepository.kt
  src/main/kotlin/dsm/pick2024/domain/user/port/out/QueryUserPort.kt
Labels: bug

#300 🔀 :: (PiCK-299)xquareId error
  src/main/kotlin/dsm/pick2024/domain/application/service/ApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/application/service/QueryMyApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/BackUserClassroomService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/MoveClassroomApplicationService.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/service/QueryUserMoveClassroomService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/CreateEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryMyEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/main/MainService.kt
Labels: bug

#302 🔀 :: (PiCK-301)admin attendance
  src/main/kotlin/dsm/pick2024/domain/attendance/port/in/ChangeAllAttendanceUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/in/QueryClassAllAttendanceUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/port/in/QueryClubAllAttendanceUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/request/ChangeAllAttendanceRequest.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAllAttendanceResponse.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/ChangeAllAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAllAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAllAttendanceService.kt
Labels: 기능 개발

#304 🔀 :: (PiCK-303)cant no early return
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/persistence/EarlyReturnPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/persistence/repository/EarlyReturnRepository.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/port/out/DeleteEarlyReturnPort.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/ChangeEarlyReturnStatusService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/CreateEarlyReturnService.kt
Labels: bug

#311 🔀 :: (PiCK-3010)attendance claseoom
  src/main/kotlin/dsm/pick2024/domain/application/persistence/ApplicationPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/classroom/persistence/PersistenceAdapterClassRoom.kt
Labels: bug

#321 🔀 :: (PiCK-314)ok early return error
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryAllOKEarlyReturnResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryEarlyReturnReasonResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryEarlyReturnResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryAllOKEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryAllReasonEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryClassEarlyReturnService.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/QueryFloorEarlyReturnService.kt
Labels: bug

#323 🔀 :: (PiCK-322) refactor earlyreturn response
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/persistence/EarlyReturnPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryAllOKEarlyReturnResponse.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/response/QueryEarlyReturnResponse.kt
Labels: Refactoring

#328 🔀 :: (PiCK-325)correct location erro
  src/main/kotlin/dsm/pick2024/domain/attendance/exception/InvalidTimeException.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/presentation/dto/response/QueryAllAttendanceResponse.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClassAllAttendanceService.kt
  src/main/kotlin/dsm/pick2024/domain/attendance/service/QueryClubAllAttendanceService.kt
  src/main/kotlin/dsm/pick2024/global/error/exception/ErrorCode.kt
Labels: bug

#330 🔀 :: (PiCK-329) status sort erreo
  src/main/kotlin/dsm/pick2024/domain/status/service/QueryClassStatusService.kt
Labels: bug

#332 🔀 :: (PiCK-331) story sort error
  src/main/kotlin/dsm/pick2024/domain/applicationstory/service/QueryClassUserService.kt
Labels: bug

#344 🔀 :: (PiCK-338) earlyreturn no error
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/service/ChangeEarlyReturnStatusService.kt
Labels: bug

#347 🔀 :: (PiCK-335) refactor application dto
  src/main/kotlin/dsm/pick2024/domain/application/presentation/ApplicationController.kt
  src/main/kotlin/dsm/pick2024/domain/application/presentation/dto/request/ApplicationRequest.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/EarlyReturnController.kt
  src/main/kotlin/dsm/pick2024/domain/earlyreturn/presentation/dto/request/CreateEarlyReturnRequest.kt
  src/main/kotlin/dsm/pick2024/global/annotation/ValidFormat.kt
  src/main/kotlin/dsm/pick2024/global/annotation/common/FormatValidator.kt
Labels: 기능 개발

#349 🔀 :: (PiCK-348)excel grade print
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/enums/Status.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/WeekendMealPersistenceAdapter.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/persistence/repository/WeekendMealRepository.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/in/PrintExcelClassWeekendMealUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/in/QueryWeekendMealClassUseCase.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/port/out/QueryWeekendMealPort.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/presentation/WeekendMealController.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/PrintAllExcelWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/PrintClassExcelWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/QueryWeekendMealClassService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/ResetWeekendMealService.kt
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/SaveAllWeekendMealUserMealService.kt
  src/main/kotlin/dsm/pick2024/global/config/security/SecurityConfig.kt
Labels: 기능 개발

#351 🔀 :: (PiCK-350) all weekend meal excel
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/PrintAllExcelWeekendMealService.kt
Labels: 기능 개발

#353 🔀 :: (PiCK-352) application schedule error
  src/main/kotlin/dsm/pick2024/infrastructure/schedule/ScheduleService.kt
Labels: bug

#355 🔀 :: (PiCK-352) add summary sheet
  src/main/kotlin/dsm/pick2024/domain/weekendmeal/service/PrintAllExcelWeekendMealService.kt
Labels: 기능 개발
